# Generated by Django 2.0 on 2019-07-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_team1',
            field=models.CharField(max_length=50),
        ),
    ]
